### ISSUE TITLE
Separate PriceTrack entity in 2 entities

### ISSUE THREAD

**Issue by UmanetAlexandru** [UmanetAlexandru/price-tracking-extension#10]
Seaparate PriceTrack entity in 2 entities one that holds the contact info (email) and one that holds all price tracking data, so that 2 email can link to same price tracking.
Also make sure that a price track is added only one time in database.

**Comment by strdr4605** [comment]
How is the price track identified? by URL?

Maybe a database scheme and other diagrams in README would clarify the architecture?

**Comment by UmanetAlexandru** [comment]
I'll add DB scheme and a better description after this task.
